name: "Run Prettier for PR"
on:
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      - name: Prettify the JS Code
        uses: creyD/prettier_action@master
        with:
          prettier_options: "--write src/*.js"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
